// Code generated by "stringer -type=Token -linecomment -output stringers.go ."; DO NOT EDIT.

package pato

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokUndefined-0]
	_ = x[TokIllegal-1]
	_ = x[TokNewline-2]
	_ = x[TokLParen-3]
	_ = x[TokRParen-4]
	_ = x[TokLBrace-5]
	_ = x[TokRBrace-6]
	_ = x[TokLBracket-7]
	_ = x[TokRBracket-8]
	_ = x[TokPlus-9]
	_ = x[TokMinus-10]
	_ = x[TokAsterisk-11]
	_ = x[TokSlash-12]
	_ = x[TokIntLit-13]
	_ = x[TokIDENT-14]
	_ = x[TokEOF-15]
	_ = x[keywordBeg-16]
	_ = x[TokIf-17]
	_ = x[TokElse-18]
	_ = x[TokFor-19]
	_ = x[keywordEnd-20]
}

const _Token_name = "undefinedillegal\\n(){}[]+-*/<integer literal><identifier>EOFkeywordBegifelseforkeywordEnd"

var _Token_index = [...]uint8{0, 9, 16, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 45, 57, 60, 70, 72, 76, 79, 89}

func (i Token) String() string {
	if i >= Token(len(_Token_index)-1) {
		return "Token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
